# Generated by Django 3.2.7 on 2021-12-10 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_cmts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmt', models.CharField(max_length=2000)),
                ('Member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.members')),
            ],
        ),
        migrations.DeleteModel(
            name='product_cmt',
        ),
        migrations.AddField(
            model_name='products',
            name='product_img',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='Member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.members'),
        ),
        migrations.AlterField(
            model_name='order_products',
            name='Member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.members'),
        ),
        migrations.AlterField(
            model_name='order_products',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.products'),
        ),
        migrations.AddField(
            model_name='product_cmts',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.products'),
        ),
    ]
