# Generated by Django 3.2.7 on 2021-12-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0003_auto_20211210_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_products',
            name='product_img',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
