# Generated by Django 3.2.7 on 2021-12-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_order_products_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_products',
            name='product_img',
        ),
    ]
