# Generated by Django 3.2.7 on 2021-12-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0005_remove_order_products_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
